### ISSUE TITLE
issues with imports under windows

### ISSUE THREAD

**Issue by tswaters** [C2FO/nools#192]
Consider the following:

./app/index.js
./lib/nools/rules/rule1.nools
./lib/nools/rules/rule2.nools

If in index.js, 
```js
nools.compile('../nools/rules/nule1.nools', { /*..etc..*/ })
```

and in rule1.nools,
```
import("./rule2.nools")
```

```
D:\Code\nools-test\cd .\app\
D:\Code\nools-test\app>node index.js
D:\Code\nools-test\node_modules\nools\lib\parser\nools\nool.parser.js:22
                    throw new Error("Invalid " + blockType + " definition \n" + e.message + "; \nstarting at : " + orig);
                    ^

Error: Invalid import definition
ENOENT: no such file or directory, open 'D:\Code\nools-test\app\rule2.nools';
starting at : import("./rule2.nools")

    at parse (D:\Code\nools-test\node_modules\nools\lib\parser\nools\nool.parser.js:22:27)
    at Object.exports.parse (D:\Code\nools-test\node_modules\nools\lib\parser\nools\nool.parser.js:35:5)
    at Object.exports.parseRuleSet (D:\Code\nools-test\node_modules\nools\lib\parser\index.js:15:27)
    at Object.exports.parse (D:\Code\nools-test\node_modules\nools\lib\compile\index.js:144:19)
    at parse (D:\Code\nools-test\node_modules\nools\lib\index.js:24:23)
    at Object.exports.compile (D:\Code\nools-test\node_modules\nools\lib\index.js:58:16)
    at Object.<anonymous> (D:\Code\nools-test\app\index.js:3:7)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
```

Under windows, the path using '/' is not recognized and it will think it's a global import and return the path to the current directory.

**Comment by tswaters** [comment]
Also, the `pathSep` variable here is not platform independent.... one must use "\\" in windows and "/" under unix to import their rules....  If this check just doesn't exist, (I'm not sure why it does), this second problem goes away.
